# Nome da aplicação
spring.application.name=FightTracker

# ===============================
# DATABASE - PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/FightTrackerDb
spring.datasource.username=postgres
spring.datasource.password=Siena5173

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# PORT (opcional)
# ===============================
server.port=8080

# ===============================
# JWT (opcional - se quiser externalizar depois)
# ===============================
# jwt.secret=minha-chave-super-secreta
# jwt.expiration=3600000